// <auto-generated />
namespace GroupProject1025.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddAllClasses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAllClasses));
        
        string IMigrationMetadata.Id
        {
            get { return "202110281722450_AddAllClasses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
